version: '2'
services:
  notification-mongodb:
    image: mongo:4.0.13
    ports:
      - '27017:27017'
    command: mongos --configdb notification-mongodb-config
  notification-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  notification-mongodb-config:
    image: mongo:4.0.13
    container_name: notification-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
